CREATE DATABASE agc;

USE agc;

CREATE TABLE Cliente(
Nome VARCHAR(45) NOT NULL,
Telefone BIGINT(11) NOT NULL
);

CREATE TABLE Agendamento(
B_Login VARCHAR(15) NOT NULL,
C_Telefone BIGINT(11) NOT NULL,
Estado CHAR(1) NOT NULL,
Horario DATETIME NOT NULL,
Id_Agendamento INT NOT NULL
);

CREATE TABLE Barbeiro(
Nome VARCHAR(45) NOT NULL,
Telefone BIGINT(11) NOT NULL,
Login VARCHAR(15) NOT NULL,
Senha  VARCHAR(45) NOT NULL
);

CREATE TABLE Folga(
Id_Folga INT NOT NULL,
Inicio DATETIME NOT NULL,
Fim DATETIME NOT NULL,
B_Login VARCHAR(15) NOT NULL
);

