USE agc;

ALTER TABLE Cliente
ADD CONSTRAINT Pk_Cliente
PRIMARY KEY (Telefone);

ALTER TABLE Agendamento
ADD CONSTRAINT Pk_Agendamento
PRIMARY KEY  (Id_Agendamento) ;

ALTER TABLE Agendamento
CHANGE Id_Agendamento Id_Agendamento INT NOT NULL AUTO_INCREMENT ;

ALTER TABLE Barbeiro
ADD CONSTRAINT Pk_Barbeiro
PRIMARY KEY (Login);

ALTER TABLE Folga
ADD CONSTRAINT Pk_Folga
PRIMARY KEY  (Id_Folga);

ALTER TABLE Folga
CHANGE Id_Folga Id_Folga INT NOT NULL AUTO_INCREMENT ;
